from enum import Enum


class ShipmentStatus(Enum):

    SHIPMENT_CREATED = 'SHIPMENT_CREATED'
    SHIPMENT_CONFIRMED = 'SHIPMENT_CONFIRMED'
    SHIPMENT_DELIVERED = 'SHIPMENT_DELIVERED'
    SHIPMENT_CANCELLED = 'SHIPMENT_CANCELLED'
