from enum import Enum

class TransactionType(Enum):

    CURRENCY_TRANSACTION = 'CURRENCY_TRANSACTION'
    NEW_ACCOUNT_TRANSACTION = 'NEW_ACCOUNT_TRANSACTION'
    BLOCK_REWARD_TRANSACTION ='BLOCK_REWARD_TRANSACTION'
