from enum import Enum

class TransactionType(Enum):

    CURRENCY_TRANSACTION = 'CURRENCY_TRANSACTION'
    CURRENCY_BLOCKING_TRANSACTION = 'CURRENCY_BLOCKING_TRANSACTION'
    NEW_ACCOUNT_TRANSACTION = 'NEW_ACCOUNT_TRANSACTION'
    BLOCK_REWARD_TRANSACTION ='BLOCK_REWARD_TRANSACTION'
    CREATE_SHIPMENT_TRANSACTION = 'CREATE_SHIPMENT_TRANSACTION'
    CONFIRM_SHIPMENT_TRANSACTION = 'CONFIRM_SHIPMENT_TRANSACTION'
    CONFIRM_DELIVERY_TRANSACTION = 'CONFIRM_DELIVERY_TRANSACTION'
    # UPDATE_SHIPMENT_TRANSACTION = 'UPDATE_SHIPMENT_TRANSACTION'
